[package]
edition = "2021"
name = "rustexp-sycamore"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
sycamore = "0.8.2"
wee_alloc = "0.4.5"

[profile.release]
lto = true
opt-level = 'z'
strip = true
