[[hooks]]
command = "sh"
command_arguments = ["-c", "if [ ! -e tailwind.css ]; then touch tailwind.css; fi"]
stage = "pre_build"

[[hooks]]
command = "sh"
command_arguments = ["-c", "npx tailwindcss -mo tailwind.css"]
stage = "build"
